// // In apiSlice.js

// import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"; // Creates an API slice for RTK Query

// // apiSlice defines endpoints that are used to fetch or mutate data
// export const apiSlice = createApi({
//     reducerPath: "api", // This is the key under which the state of this slice will be stored in Redux state.
//     baseQuery: fetchBaseQuery({ baseUrl: "http://192.168.10.153:8081/api" }), // Base URL for the API calls
//     tagTypes: ["Todos"], // Tags to be used for caching and invalidation logic
//     endpoints: (builder) => ({
//         addTodo: builder.mutation({
//             query: (todo) => ({
//                 url: " ", // URL for adding a new todo
//                 method: "POST", // HTTP method for adding data
//                 body: todo, // Data being sent to the server
//             }),
//             invalidatesTags: ["Todos"], // Invalidates the cache when a new todo is added, forcing a refetch of the todos
//         }),
        
        
//     }),
// });

// // These are hooks auto-generated by RTK Query for querying and mutating data
// export const {  } = apiSlice;
 